<a href="https://colab.research.google.com/github/Spirited-Coder/Mnist-Dataset-Prediction-Using-Tensorflow/blob/main/Probability_Check_on_Mnist_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print("Tensorflow version:", tf.__version__)

Tensorflow version: 2.14.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 0s 0us/step


In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10),
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.20484863, -0.50352216,  0.01357181,  0.7118029 , -0.12597477,
         0.1483432 , -0.45676172, -0.5414475 , -0.64842445,  0.55407435]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.11797884, 0.05809819, 0.09743918, 0.19587164, 0.08474797,
        0.11149724, 0.06087941, 0.05593605, 0.05026114, 0.16729036]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.1937554

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2955 - accuracy: 0.9134
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1398 - accuracy: 0.9592
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1064 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0858 - accuracy: 0.9742
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0754 - accuracy: 0.9765


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0764 - accuracy: 0.9766 - 1s/epoch - 5ms/step


[0.07637681066989899, 0.9765999913215637]

In [13]:
proba_model = tf.keras.models.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [14]:
proba_model(x_test[:5]).numpy()

array([[1.3859881e-09, 1.2745571e-09, 3.4197496e-06, 4.9729219e-06,
        3.8000731e-11, 5.8818049e-08, 9.4038201e-14, 9.9998856e-01,
        2.6743521e-08, 2.8121053e-06],
       [1.6703073e-07, 4.1860738e-05, 9.9973792e-01, 1.9250337e-04,
        3.0091957e-14, 2.1965221e-05, 5.1561451e-06, 1.4276269e-11,
        4.7105158e-07, 3.5186897e-14],
       [5.1581816e-07, 9.9890840e-01, 2.6012965e-05, 3.0806505e-06,
        1.1426815e-04, 1.1633562e-05, 5.4511320e-06, 7.3404924e-04,
        1.9541735e-04, 1.1802387e-06],
       [9.9677086e-01, 8.8237090e-07, 1.4060133e-03, 2.9342211e-06,
        2.7053441e-06, 1.3875906e-05, 7.1574912e-05, 1.5540086e-03,
        1.0452654e-06, 1.7613902e-04],
       [3.0301048e-06, 5.8081602e-09, 3.4084100e-05, 9.2728897e-08,
        9.9164152e-01, 1.3504507e-06, 6.5634248e-07, 2.9641078e-04,
        3.9801575e-06, 8.0187870e-03]], dtype=float32)